import { NextRequest, NextResponse } from 'next/server';
import { transcribeAudio } from '@/lib/services/vapi';
import { extractActions } from '@/lib/services/claude';
import { sendActionEmails } from '@/lib/services/email';
import { cacheMeetingData } from '@/lib/services/redis';

interface ProcessRequest {
  jobId: string;
  filePath: string;
}

interface ProcessResponse {
  jobId: string;
  status: 'success' | 'error';
  transcript?: string;
  actions?: any[];
  emailResults?: any[];
  citedMd?: string;
  error?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: ProcessRequest = await request.json();
    const { jobId, filePath } = body;

    if (!jobId || !filePath) {
      return NextResponse.json(
        { error: 'jobId and filePath required' },
        { status: 400 }
      );
    }

    console.log(`[${jobId}] Starting processing pipeline...`);

    // Step 1: Transcribe audio
    console.log(`[${jobId}] Step 1: Transcribing audio...`);
    const transcript = await transcribeAudio(filePath);

    // Step 2: Extract action items
    console.log(`[${jobId}] Step 2: Extracting action items...`);
    const actions = await extractActions(transcript);

    // Step 3: Send emails
    console.log(`[${jobId}] Step 3: Sending emails...`);
    const emailResults = await sendActionEmails(actions, jobId);

    // Step 4: Generate cited.md
    console.log(`[${jobId}] Step 4: Generating cited.md...`);
    const citedMd = generateCitedMd(jobId, transcript, actions, emailResults);

    // Step 5: Cache everything in Redis
    console.log(`[${jobId}] Step 5: Caching to Redis...`);
    await cacheMeetingData(jobId, {
      transcript,
      actions,
      emailResults,
    });

    console.log(`[${jobId}] Processing complete!`);

    return NextResponse.json({
      jobId,
      status: 'success',
      transcript,
      actions,
      emailResults,
      citedMd,
    } as ProcessResponse);
  } catch (error) {
    console.error('Process error:', error);

    return NextResponse.json(
      {
        status: 'error',
        error: error instanceof Error ? error.message : 'Processing failed',
      },
      { status: 500 }
    );
  }
}

function generateCitedMd(
  jobId: string,
  transcript: string,
  actions: any[],
  emailResults: any[]
): string {
  const timestamp = new Date().toISOString();

  const actionsSection = actions
    .map(
      (action) =>
        `- **${action.action}**
  - Owner: ${action.owner}
  - Deadline: ${action.deadline}
  - Context: ${action.context}
  - Timestamp: ${action.timestamp}
  - Status: ${action.status}`
    )
    .join('\n\n');

  const emailsSection = emailResults
    .map(
      (result) =>
        `- **${result.recipient}**: ${result.status.toUpperCase()}${
          result.message ? ` - ${result.message}` : ''
        }`
    )
    .join('\n');

  return `# Meeting Summary — ${jobId}

**Generated:** ${timestamp}

## Meeting Transcript

\`\`\`
${transcript}
\`\`\`

## Action Items

${actionsSection}

## Email Delivery Status

${emailsSection}

---

*Generated by Meeting Agent*`;
}
